### ISSUE TITLE
Could you add some of the features from this version to yours?

### ISSUE THREAD

**Issue by ghost** [Sulpitz/QuickHeal#19]
https://github.com/codefracas/QuickHeal

Things such as the renew and main tank stuff I would love to see in your rework-healmodes-and-max-HPS branch

1.14.5
Disabled vestigial config UI tab 'Target Filtering' Fixed lua error messages that were being generated from bad OnEnter syntax in QuickHeal.xml:1620:FilterRaidGroup1-8 Revised readme.md

1.16
Added functions SmartRenew(), SmartRenewFirehose() and SmartRenewThrottle(). Revised readme.md

1.16.1
Removed functions SmartRenew(), SmartRenewFirehose() and SmartRenewThrottle(). These were causing target focus problems.
Implemented /qh hot to replace SmartRenewThrottle().
Regular SmartRenew & SmartRenewFirehose comin' soon-ish like.

1.17.0
Modified the verbiage for /qh toggle to QuickHeal mode: Normal HPS and QuickHeal mode: High HPS.
The main tanks list is now saved to disk and will persist across sessions.
Removed non-partition mode (hm) commands.
Druids can now cast HoTs while moving.
Big overhaul on usage syntax, e.g.: /qh [mask] [type] [mod] OR /quickheal [mask] [type] [mod]:

[mask]: constrains healing pool to:
player = yourself
target = your target
targettarget = your target's target
party = your party
mt = main tanks (defined in the configuration panel)
nonmt = everyone but the main tanks
subgroup = raid subgroups (defined in the configuration panel)

[type]: constrains healing spell to:
heal: Forces the use of your class' channeled heal spells.
hot: Forces the use of your class' HoT spell over a channeled spell. Only works for Priests & Druids.
chainheal: Forces the use of the Chain Heal spell. Only works for Shamans.

[mod]: optional argument. Modifies the application of HoTs:
max= will apply a HoT to the next target that is not @100% hp and that does not currently have a HoT applied.
fh = firehose mode. Will apply maximum rank HoT on the next target that does not have a HoT applied.

1.17.1
Implemented TWA button inside Main Tanks UI that queries TWAssignments' roster and automatically fills Main Tank UI with up-to-date tank assignments. Does not require TWAssignments to be installed on the local client. Requires membership to a raid in which at least one other raidmember/leader is using TWAssignments.

1.17.2
Fixed shaman class.

1.17.3
Removed /qh healpct.
Channeled heals now proactively rely entirely on HealComm to determine if another player is healing your considered target(s) during the selection process.
Each healing class now has its own syntax command tree.
Added [chainheal] healing type selection for Shaman class.

1.17.4
Re-partitioned class modules (i.e. QuickHealDruid.lua, QuickHealPriest.lua, QuickHealPaladin.lua, QuickHealShaman.lua) to allow for class-specific spell/item cast sequences.

1.17.5
Added 4 new keybindings:

"HoT" [/qh hot]
"HoT Firehose (Naxx Gargoyles)" [/qh hot fh]
"HoT Subgroup" [/qh subgroup hot]
"HoT MT" [/qh mt hot]
1.17.6
Druid healing improvements & Shaman chainheal fix.

Druid: Modified downrank sliders that control Healing Touch and Regowth maximum ranks
Druid: Split QuickHeal_Druid_FindHealSpellToUse into two separate function blocks: one for <L60 healing and one for =L60
Druid: Removed "Cfg->General->Healthy Threshold Slider/RatioHealthy" slider and explanation text;
Druid: Eliminated all in-combat HT ranks above HT4 if =L60.
Druid: When in Normal HPS mode, HT4 will be cast over HT3 if Nature's Grace procs.
Shaman: Fixed intermittent ChainHeal SpellID error

**Comment by shikulja** [comment]
Support for this fork by the author has ended.

**Comment by ghost** [comment]
@shikulja it can be reuploaded

**Comment by Zebouski** [comment]
@shikulja They are still working on their fork, they just don't wanna publish it themselves anymore. I have it published under this mirror on my account and I will be updating it from the author. 

https://github.com/Zebouski/QuickHeal

**Comment by shikulja** [comment]
@Gurky-Turtle @Zebouski
codefracas is an experienced developer, it will be easier for him to merge branches, as he knows his own changes better.
His branch is interesting to me and I will observe if there is an opportunity of course.

Pull requests are open here if anyone wants to work on it.

I managed to transfer the interface from the fork, but there is no more interest in doing it.
[rework+TWA_UI.zip](https://github.com/Sulpitz/QuickHeal/files/11348097/rework%2BTWA_UI.zip)

I also transferred the localization and libraries for his branch, but I could not check and fix it for the pull request, since his version does not work for me
[QuickHeal___fork.zip](https://github.com/Sulpitz/QuickHeal/files/11348113/QuickHeal___fork.zip)

**Comment by Sulpitz** [comment]
Hi,
as you guys see, I'm not active in the Vanilla addon scene any more. I'm happy tho, that my improvements on QuickHeal live on and are improved themselves.
If you want to appoint more contributors @shikulja we can do that.

**Comment by shikulja** [comment]
https://github.com/Sulpitz/QuickHeal/issues/23

**Comment by shikulja** [comment]
last fork qh_TW here
[Sulpitz](https://github.com/Sulpitz/QuickHeal/issues/19) > [codefracas](https://github.com/codefracas/QuickHeal) > https://github.com/Zebouski/QuickHeal > [Eirosdev](https://github.com/Eirosdev) > https://github.com/Bestoriop/QuickHeal

I think QH is going down a strange path. They should have added compatibility checking for 1.12 and TW, and then used one or the other client compatible healing functions.
HealComm got changes for TW too, and the correct thing to do would have been to add TW checking too, rather than replacing the common calculation tables, or at least renaming HealCommTW-1.0

**Comment by Zebouski** [comment]
@shikulja is there any longer a need for my mirror
